services:
  db:
    image: mysql:8.0.37
    restart: unless-stopped
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: castiautilsdev
      MYSQL_USER: castiautilsuser
      MYSQL_PASSWORD: castiautilspassword
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      PMA_HOST: db
      PMA_USER: castiautilsuser
      PMA_PASSWORD: castiautilspassword

volumes:
  db_data:
